/**
 * Texas Statutory Durable Power of Attorney — PDF Template
 *
 * Composes the section components into a complete document. Sections are
 * ordered to match § 752.051's canonical structure:
 *
 *   1. Title + statutory NOTICE
 *   2. Agent designation (principal + agent + successor)
 *   3. Grant of general powers (initial-each)
 *   4. Grant of hot powers (separate initialing)
 *   5. Effective date + durability declaration
 *   6. Signature + agent fiduciary notice + notary acknowledgment
 *
 * Receives the full wizard state and an optional `watermarked` flag. When
 * watermarked is true, the DRAFT overlay renders on every page.
 *
 * Footer shows page number and (if watermarked) the preview notice.
 */

import { Document, Page, Text, View } from "@react-pdf/renderer";
import { styles, FONTS, SIZES, COLORS } from "./styles";
import { Header } from "./sections/Header";
import { Designation } from "./sections/Designation";
import { Powers } from "./sections/Powers";
import { HotPowers } from "./sections/HotPowers";
import { EffectiveDate } from "./sections/EffectiveDate";
import { Signature } from "./sections/Signature";
import { Watermark } from "./sections/Watermark";

export function TexasPoaDocument({ wizardState, watermarked = true }) {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const sessionId = wizardState.sessionId || "preview";

  return (
    <Document
      title="Texas Statutory Durable Power of Attorney"
      author="POA-IT"
      subject="Statutory Durable Power of Attorney under Tex. Est. Code § 752.051"
      keywords="Texas, Power of Attorney, Statutory, Durable, § 752.051"
    >
      <Page size="LETTER" style={styles.page}>
        {watermarked && <Watermark />}

        <Header />
        <Designation wizardState={wizardState} />
        <Powers wizardState={wizardState} />
        <HotPowers wizardState={wizardState} />
        <EffectiveDate wizardState={wizardState} />
        <Signature wizardState={wizardState} />

        {/* Footer: page numbers + provenance */}
        <View style={styles.footer} fixed>
          <Text>POA-IT · Texas Statutory Durable POA · {dateStr}</Text>
          <Text
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>

        {/* Provenance footer line — invisible-ish, helps with chain of custody */}
        <View
          style={{
            position: "absolute",
            bottom: 10,
            left: SIZES.PAGE_MARGIN,
            right: SIZES.PAGE_MARGIN,
          }}
          fixed
        >
          <Text style={{ fontSize: 7, color: COLORS.GRAY, textAlign: "center" }}>
            Document ID: {sessionId} · Generated by POA-IT (poa-it.com)
          </Text>
        </View>
      </Page>
    </Document>
  );
}
