/**
 * Document Generation Certificate.
 *
 * Sprint 4b.1 Round 3 — attorney-recommended addition. The certificate
 * provides operational proof of what the wizard captured, helping law
 * firms, agents, financial institutions, and POA-IT support confirm that
 * the PDF accurately reflects user choices.
 *
 * Per attorney: "This does not replace the legal text, but it helps law
 * firms, agents, financial institutions, and your own support team confirm
 * that the PDF accurately reflects the wizard choices."
 *
 * Renders as a separate page at the end of the document (after Important
 * Information for Agent) via break={true}.
 *
 * The Document Hash is computed AFTER the PDF is rendered (the PDF would
 * change if hash were computed before render), and is inserted into the
 * file via a post-processing step in generatePdf.js. For preview drafts,
 * the hash field shows "—" since the hash isn't meaningful for previews.
 *
 * NOTE: Template versioning + hash backend is part of Sprint 4e (Template
 * Versioning + Tamper Evidence). For Round 3, we render the certificate
 * structure with the values we have today; the hash field is reserved.
 */

import { View, Text } from "@react-pdf/renderer";
import { styles, SIZES, COLORS, FONTS } from "../styles";

const TEMPLATE_VERSION = "Texas SDPOA v2026.05.22";
const JURISDICTION = "Texas";

export function DocumentGenerationCertificate({ wizardState, watermarked }) {
  const principalName = wizardState.principalFullLegalName || "—";
  const agentName = wizardState.agentFullLegalName || "—";
  const successorName = wizardState.successorAgentFullLegalName || "Not designated";

  const powersSelected = formatPowersSelected(wizardState.powersGranted);
  const hotPowersSelected = formatHotPowersSelected(wizardState.hotPowersGranted);

  const effectiveDate =
    wizardState.effectivenessType === "springing"
      ? "Upon physician determination of disability or incapacity"
      : "Immediately upon execution";

  const executionMethod =
    wizardState.executionMethod === "ron"
      ? "Texas online notarization (RON)"
      : wizardState.executionMethod === "in_person"
      ? "Texas in-person notarization"
      : "Not yet selected";

  const sessionId = wizardState.sessionId || "preview";
  const generatedAt = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";

  const documentStatus = watermarked ? "Draft Preview" : "Signing-Ready Copy";

  return (
    <View break>
      <Text style={[styles.title, { fontSize: 14, marginBottom: 4 }]}>
        Document Generation Certificate
      </Text>

      <Text
        style={{
          fontFamily: FONTS.SANS,
          fontSize: 9,
          color: COLORS.GRAY,
          textAlign: "center",
          letterSpacing: 0.3,
          marginBottom: SIZES.SECTION_SPACING,
        }}
      >
        This certificate is generated by POA-IT to document the wizard
        selections embedded in this Power of Attorney. It is metadata, not
        legal authority — the operative legal text appears earlier in this
        document.
      </Text>

      <CertField label="Document Status" value={documentStatus} highlight />
      <CertField label="Document Type" value="Texas Statutory Durable Power of Attorney" />
      <CertField label="Jurisdiction" value={JURISDICTION} />
      <CertField label="Template Version" value={TEMPLATE_VERSION} />
      <CertSeparator />

      <CertField label="Principal" value={principalName} />
      <CertField label="Agent" value={agentName} />
      <CertField label="Successor Agent" value={successorName} />
      <CertSeparator />

      <CertField label="General Powers Selected" value={powersSelected} multiline />
      <CertField label="Specific (Hot) Powers Selected" value={hotPowersSelected} multiline />
      <CertSeparator />

      <CertField label="Effective Date" value={effectiveDate} />
      <CertField label="Execution Method" value={executionMethod} />
      <CertField label="Compensation Selection" value={formatCompensation(wizardState)} multiline />
      <CertSeparator />

      <CertField label="Authority Selection Method" value="POA-IT wizard" />
      <CertField label="Document ID" value={String(sessionId).slice(0, 16)} mono />
      <CertField label="Generated At" value={generatedAt} mono />
      <CertField
        label="Document Hash (SHA-256)"
        value={watermarked ? "— (not computed for draft preview)" : "{{DOC_HASH_PLACEHOLDER}}"}
        mono
      />

      <View
        style={{
          marginTop: SIZES.SECTION_SPACING,
          padding: 10,
          backgroundColor: "#F7F7F7",
          borderLeftWidth: 2,
          borderLeftColor: "#999999",
        }}
      >
        <Text style={[styles.bodyTight, styles.italic, { fontSize: 9.5 }]}>
          Document integrity verification is handled by POA-IT. The final
          executed document will include or be associated with a SHA-256 hash
          generated after execution. For questions about verification, contact{" "}
          <Text style={{ fontFamily: FONTS.SANS_BOLD }}>support@poa-it.com</Text>.
        </Text>
      </View>
    </View>
  );
}

function CertField({ label, value, highlight, multiline, mono }) {
  const valueFontFamily = highlight
    ? "Times-Bold"
    : mono
    ? "Courier"
    : FONTS.SERIF;

  return (
    <View
      style={{
        flexDirection: multiline ? "column" : "row",
        marginBottom: 6,
        alignItems: multiline ? "flex-start" : "baseline",
      }}
      wrap={false}
    >
      <Text
        style={{
          fontFamily: FONTS.SANS_BOLD,
          fontSize: 9,
          color: COLORS.GRAY,
          letterSpacing: 0.5,
          textTransform: "uppercase",
          width: multiline ? "100%" : 180,
          marginBottom: multiline ? 3 : 0,
        }}
      >
        {label}
      </Text>
      <Text
        style={{
          fontFamily: valueFontFamily,
          fontSize: highlight ? 11 : 10,
          color: COLORS.INK,
          flex: multiline ? undefined : 1,
        }}
      >
        {value}
      </Text>
    </View>
  );
}

function CertSeparator() {
  return (
    <View
      style={{
        borderBottomWidth: 0.5,
        borderBottomColor: "#D4D4D8",
        marginVertical: 8,
      }}
    />
  );
}

// Map the wizard state's powersGranted array into a human-readable list
const POWER_LABELS = {
  real_property: "(A) Real property transactions",
  tangible_personal_property: "(B) Tangible personal property transactions",
  stocks_and_bonds: "(C) Stock and bond transactions",
  commodity_and_option: "(D) Commodity and option transactions",
  banking_and_financial: "(E) Banking and other financial institution transactions",
  business_operating: "(F) Business operating transactions",
  insurance_and_annuity: "(G) Insurance and annuity transactions",
  estate_trust_beneficiary: "(H) Estate, trust, and other beneficiary transactions",
  claims_and_litigation: "(I) Claims and litigation",
  personal_and_family_maintenance: "(J) Personal and family maintenance",
  government_benefits: "(K) Benefits from social security, Medicare, Medicaid, etc.",
  retirement_plan: "(L) Retirement plan transactions",
  tax_matters: "(M) Tax matters",
  digital_assets: "(N) Digital assets and the content of an electronic communication",
  all_powers: "(O) ALL powers listed in (A) through (N)",
};

function formatPowersSelected(powersGranted) {
  const granted = Array.isArray(powersGranted) ? powersGranted : [];
  if (granted.length === 0) return "None";
  if (granted.includes("all_powers")) {
    return POWER_LABELS.all_powers;
  }
  return granted
    .map((k) => POWER_LABELS[k] || k)
    .join("\n");
}

/**
 * Format the compensation selection for the certificate.
 *
 * Sprint 4b.3 — per attorney guidance: "the certificate should reconcile
 * against actual user choice. Compensation selection: No option initialed;
 * statutory default acknowledged by principal."
 *
 * Three states:
 *   - User picked "reasonable" → "Reimbursement of expenses plus reasonable compensation"
 *   - User picked "no_compensation" → "Reimbursement of expenses only; no compensation"
 *   - User left blank → "No option initialed; statutory default acknowledged by principal"
 */
function formatCompensation(wizardState) {
  const choice = wizardState.agentCompensation;
  if (choice === "reasonable") {
    return "Reimbursement of expenses plus reasonable compensation (initialed by principal)";
  }
  if (choice === "no_compensation") {
    return "Reimbursement of expenses only; no compensation for serving (initialed by principal)";
  }
  return "No option initialed; statutory default acknowledged by principal";
}

// Sprint 4b.2 fix: labels keyed to wizard's actual keys. Prior version used
// long-form keys that never matched the wizard, exposing raw tokens like
// "hot_power_gifts" in the rendered certificate.
const HOT_POWER_LABELS = {
  hot_power_trust: "Create, amend, revoke, or terminate an inter vivos trust",
  hot_power_gifts: "Make a gift (subject to § 751.032 limits)",
  hot_power_survivorship: "Create or change rights of survivorship",
  hot_power_beneficiary: "Create or change a beneficiary designation",
  hot_power_delegate: "Authorize another person to exercise authority",
};

function formatHotPowersSelected(hotPowersGranted) {
  const granted = Array.isArray(hotPowersGranted) ? hotPowersGranted : [];
  if (granted.length === 0) return "None";
  return granted
    .map((k) => HOT_POWER_LABELS[k] || humanize(k))
    .join("\n");
}

/**
 * Defensive fallback: if a key slips through that isn't in HOT_POWER_LABELS,
 * humanize it instead of rendering the raw token. e.g.,
 *   "hot_power_some_new_thing" → "Some new thing"
 * Prevents internal tokens from ever leaking to users.
 */
function humanize(key) {
  return String(key)
    .replace(/^hot_power_/, "")
    .replace(/_/g, " ")
    .replace(/^\w/, (c) => c.toUpperCase());
}
