import { LegalLayout } from "../../../components/LegalLayout";

export const metadata = {
  title: "Terms of Service — POA-IT",
  description: "Terms of Service for the POA-IT power-of-attorney service.",
};

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms of Service"
      effectiveDate="To be set at launch"
      lastUpdated="May 2026 (draft, pending Texas counsel review)"
    >
      <div className="callout">
        <strong>Plain-English summary:</strong> POA-IT is software that helps Texas
        residents create power-of-attorney documents. We are not a law firm and do
        not give legal advice. If you need legal advice, we can refer you to a
        licensed Texas attorney through our Marketplace. You retain full ownership
        of your documents and your data.
      </div>

      <h2>1. POA-IT is not a law firm</h2>
      <p>
        <strong>POA-IT IS NOT A LAW FIRM AND DOES NOT PROVIDE LEGAL ADVICE.</strong> The
        Service is self-help legal technology. The information, forms, and documents
        provided through the Service are not a substitute for the advice of an
        attorney. Using the Service does not create an attorney-client relationship
        between you and POA-IT.
      </p>
      <p>
        The Service operates under the safe harbor of <span className="citation">Tex.
        Gov't Code § 81.101(c)</span>. If you have legal questions about your specific
        circumstances, you should consult a licensed Texas attorney.
      </p>

      <h2>2. The Service</h2>
      <p>
        POA-IT provides software that allows you to generate Texas power-of-attorney
        documents from information you provide. The Service may include document
        templates, a guided wizard, electronic notarization through third-party
        providers, an encrypted document vault, and an attorney referral marketplace.
      </p>
      <p>
        The Service is currently in pre-launch and will be available to Texas residents.
        We may expand coverage to additional U.S. states in the future and these Terms
        will be updated when we do.
      </p>

      <h2>3. Eligibility</h2>
      <p>You must be at least 18 years old to create an account or generate a document. By using the Service, you represent that:</p>
      <ul>
        <li>You are at least 18 years of age (or 17 and emancipated)</li>
        <li>You are mentally competent to enter into binding legal documents</li>
        <li>The information you provide is true and accurate</li>
        <li>You are using the Service for yourself, not creating a document for another person without that person's knowledge and consent</li>
      </ul>

      <h2>4. Your account</h2>
      <p>
        You are responsible for maintaining the confidentiality of your account
        credentials and for all activity that occurs through your account. Notify us
        immediately at security@poa-it.com if you suspect unauthorized access.
      </p>
      <p>You may delete your account at any time.</p>

      <h2>5. Acceptable use</h2>
      <p>You may use the Service only for lawful personal or business purposes. You may NOT:</p>
      <ul>
        <li>Use the Service to create documents intended to defraud, deceive, or harm another person</li>
        <li>Provide false information about yourself, your agent, or the principal of any POA</li>
        <li>Use the Service to commit elder financial abuse, fraud, or any criminal offense (including violations of <span className="citation">Tex. Penal Code §§ 32.45, 32.53, 32.55, or 38.122</span>)</li>
        <li>Reverse engineer, scrape, or attempt to extract source materials from the Service</li>
        <li>Resell, redistribute, or relabel documents generated by the Service for commercial gain</li>
        <li>Use the Service to practice law on behalf of others</li>
      </ul>

      <h2>6. Fees, refunds, and payment</h2>
      <p>
        Fees for the Service are displayed at checkout and are payable in advance
        through our payment processor (Stripe). All fees are in U.S. dollars. You
        authorize us to charge the payment method you provide.
      </p>
      <p>See our <a href="/legal/refunds">Refund Policy</a> for complete refund terms.</p>

      <h2>7. Intellectual property</h2>
      <p>
        The Service, including all software, content, designs, and trademarks, is
        owned by POA-IT or our licensors. We grant you a limited, non-exclusive,
        non-transferable license to use the Service for the personal purpose of
        generating power-of-attorney documents.
      </p>
      <p>
        <strong>You own the data you input. You own the final generated document.</strong>{" "}
        POA-IT retains no rights in your document beyond maintaining a copy in your
        vault while your account is active.
      </p>

      <h2>8. Attorney Marketplace</h2>
      <p>
        POA-IT provides a directory of independent licensed Texas attorneys who
        have indicated availability to assist customers. POA-IT does NOT employ,
        supervise, or share fees with these attorneys. We do not provide referrals
        based on the merits of your matter. Any engagement you enter with an
        attorney is strictly between you and that attorney. POA-IT receives no
        contingent compensation from attorney fees you pay.
      </p>

      <h2>9. Disclaimer of warranties</h2>
      <p>
        EXCEPT AS EXPRESSLY STATED, THE SERVICE IS PROVIDED "AS IS" AND "AS
        AVAILABLE." TO THE FULLEST EXTENT PERMITTED BY LAW, POA-IT DISCLAIMS ALL
        WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
      </p>
      <p>
        POA-IT warrants only that the document generated through the Service
        reflects the Texas statutory form set forth in the applicable Texas statute
        as it exists on the date of generation. We do not warrant:
      </p>
      <ul>
        <li>That any specific bank, hospital, title company, or other third party will accept the document, although Texas law (<span className="citation">Tex. Est. Code §§ 751.201–751.213</span>) generally requires acceptance</li>
        <li>That the document is sufficient for any particular legal matter beyond what its statutory form contemplates</li>
        <li>That changes in Texas law after the date of generation will not affect the document</li>
      </ul>
      <p>If a defect in our software causes a document to not conform to the statutory form on the date of generation, we will reissue at no charge. This is your sole remedy.</p>

      <h2>10. Limitation of liability</h2>
      <p>
        TO THE FULLEST EXTENT PERMITTED BY LAW, POA-IT'S AGGREGATE LIABILITY
        ARISING OUT OF OR RELATED TO THE SERVICE SHALL NOT EXCEED THE GREATER OF
        (a) ONE HUNDRED DOLLARS ($100), OR (b) THE AMOUNT YOU PAID POA-IT IN THE
        TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO LIABILITY.
      </p>
      <p>
        IN NO EVENT SHALL POA-IT BE LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL,
        PUNITIVE, OR SPECIAL DAMAGES, INCLUDING WITHOUT LIMITATION LOST PROFITS,
        LOST DATA, OR DAMAGES FROM THIRD-PARTY REFUSAL TO ACCEPT YOUR DOCUMENT.
      </p>
      <p>These limitations do not apply to (i) damages caused by our gross negligence or intentional misconduct, (ii) personal injury or death caused by our negligence, or (iii) any liability that cannot be limited under applicable Texas law.</p>

      <h2>11. Indemnification</h2>
      <p>You agree to indemnify, defend, and hold harmless POA-IT and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of your breach of these Terms, your misuse of the Service, your provision of false information, your use of a generated document to commit fraud or harm another person, or your violation of any law.</p>

      <h2>12. Arbitration and class action waiver</h2>
      <p>
        <strong>PLEASE READ CAREFULLY.</strong> Any dispute arising out of or relating
        to these Terms or the Service shall be resolved by binding arbitration under
        the Consumer Arbitration Rules of the American Arbitration Association
        ("AAA"). The arbitration shall be conducted in Travis County, Texas or
        remotely at your election.
      </p>
      <p>
        <strong>YOU AND POA-IT EACH WAIVE THE RIGHT TO BRING OR PARTICIPATE IN A
        CLASS ACTION, COLLECTIVE ACTION, OR REPRESENTATIVE PROCEEDING.</strong>
      </p>
      <p>This arbitration agreement does not apply to small-claims-court proceedings within the court's jurisdictional limits or to claims to enforce intellectual property rights. You may opt out within 30 days of first accepting these Terms by emailing arbitration-opt-out@poa-it.com.</p>

      <h2>13. Termination</h2>
      <p>We may suspend or terminate your account if we reasonably believe you have violated these Terms, applicable law, or the rights of a third party. You may terminate your account at any time. On termination, your generated documents remain yours; we will provide a download of any documents stored in your vault for at least 30 days following termination.</p>

      <h2>14. Choice of law and venue</h2>
      <p>These Terms are governed by the laws of the State of Texas, without regard to its conflict-of-laws provisions. Subject to Section 12, any court proceeding shall be brought exclusively in the state or federal courts located in Travis County, Texas.</p>

      <h2>15. Changes to these Terms</h2>
      <p>We may update these Terms from time to time. Material changes will be posted on the Service and emailed to active account holders at least 30 days before the effective date.</p>

      <h2>16. Contact</h2>
      <p>
        POA-IT Inc.<br />
        Austin, Texas<br />
        <a href="mailto:support@poa-it.com">support@poa-it.com</a> · <a href="mailto:legal@poa-it.com">legal@poa-it.com</a>
      </p>
    </LegalLayout>
  );
}
